spring:
  application:
    name: 'usuario'
  datasource:
    username: root 
    password: 123456
    url: jdbc:mysql://localhost:3306/usuario
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081
  servlet:
    context-path: /user
  